### ISSUE TITLE
Certbot not configured with the new domain.

### ISSUE THREAD

**Issue by ktrvs** [ediblewiki/issue-tracking#2]
Because of the domain switch to ediblewiki.info, the SSL certificate needs to be updated for that new domain.

Members are encouraged not to sign in while we work on this issue.

**Comment by duckboycool** [comment]
As of right now, if edits need to be made, you can use the old site which is still secure.

The link is here: https://edible-wiki.ddns.net/wiki/Edible_Wiki_Home

_Note:_ Using a link without a subdomain will result in a redirect to the new wiki, so use one with a subdomain.

**Comment by Kenny2github** [comment]
Fixed.
