### ISSUE TITLE
Top of main logo is cut of slightly. 

### ISSUE THREAD

**Issue by ktrvs** [ediblewiki/issue-tracking#6]
I think this can be fixed by editing the resolution of the logo slightly.

**Comment by duckboycool** [comment]
I already have one with the correct resolution, which I showed a few months ago shortly after the wiki was made, but Banana said it couldn't be updated for some reason.

**Comment by duckboycool** [comment]
The problem is worse in vector, where there is about 100px gap below the image.

**Comment by ktrvs** [comment]
@duckboycool Can you quickly upload the correct resolution here and I'll look?

**Comment by duckboycool** [comment]
https://cdn.discordapp.com/attachments/353241887693471747/422135442729861121/oie_transparent_7.png I had it pinned in the Discord.

**Comment by ktrvs** [comment]
👍
